# this version: organized into what is saved on cloud vs. saved on local

experimentName = "greenEyes"
experimentId = 1
model = "greenEyes"

rtData = true
date = "today" # "2018-08-16"  # or "today", "now", "2018-03-01" or "03/01/2018" etc.
subjectName = "061819_greenEyes"
subjectNum = 4
subjectDay = 2
mode = "local"  #"debug"
machine = "intel" #"cluster"
interpretation = "random"  #"random" # will either be 'C', 'P', or 'random'
# subject 101 - 2/18/19, runs 1-3 were scans 7,8,9, -- P,P,C
# subject 102 - 2/19/19, runs 1-4 were scans 9-12 -- C,C,P,P

# MODE OPTIONS
# 1 - LOCAL -- PROCESSING ON LINUX
# 2 - CLOUD -- PROCESSING FROM LINUX TO CLOUD
# 3 - DEBUG -- PROCESSING ON CLUSTER TO CLUSTER

# MACHINE OPTIONS FOR PREPARING FOLDERS
# 1 - INTEL -- RUNNING CODE ON INTEL LINUX CURRENTLY
# 2 - CLOUD -- RUNNING CODE ON CLOUD CURRENTLY
# 3 - CLUSTER -- RUNNING ON CLUSTER

# STORY PARAMETERS
story_TR_1 = 14
story_TR_2 = 464
fileNum_story_TR_1 = 25
fileNum_story_TR_2 = 475
nTR_run = 485
nTR_skip = 10 # number of TRs to skip at the beginning of the run
nVox=2414
removeAvg = 1
k1=0
k2=25
## EXP DESIGN ##
# CHEATING = 1
# PARANOID = 2
contextNum = 2 # or randomize at the start which context to set them to?
MNI_ref_BOLD="mni_icbm152_t1_tal_nlin_asym_09c_BOLD_brain.nii.gz"
MASK="TOM_large_resampled_maskedbybrain.nii.gz"

## CLASSIFIER NAMES ##
classifierNamePattern = "UPPERRIGHT_stationInd_{}_ROI_1_AVGREMOVE_1_filter_0_k1_0_k2_25.sav"
averageSignal = "averageSignal_ROI_1_AVGREMOVE_1_filter_0_k1_0_k2_25.npy"
stationDict = "upper_right_winners_nofilter.npy"

## EXP DESIGN ##
buildImgPath = true
serverDataDir = "data/server"
findNewestPatterns = true
watchFilePattern = "*.dcm"
minExpectedDicomSize = 300000
retrieveServerFiles = false
enforceDeadlines = true
calcClockSkewIters = 30
# Specify default run numbers
Runs = [1, 2, 3, 4]
ScanNums = [5, 6 ,7 ,8]
totalNumberRuns = 4

## DISPLAY PARAMETERS ##
[display]
debug = 0
useButtonBox = 1
rtData = 1
usePython = 1

# ON LOCAL (INTEL LINUX)
[intelrt]
imgDir = "/Data1/subjects/"
codeDir = "/Data1/code/rt-cloud/projects/greenEyes/"
classifierDir="/Data1/code/utils_greenEyes/greenEyes_clf/"
maskDir="/Data1/code/utils_greenEyes/greenEyes_masks/"
dicomNamePattern = "001_0000{}_000{}.dcm"

# ON CLOUD VM (WHEN USING CLOUD)
[cloud]
codeDir = "/home/amennen/code/rt-cloud/projects/greenEyes/"
classifierDir = "/home/amennen/utils/greenEyes_clf/"
maskDir = "/home/amennen/utils/greenEyes_masks"

# ON CLUSTER 
[cluster]
codeDir = "/jukebox/norman/amennen/github/brainiak/rt-cloud/projects/greenEyes/"
clusterBidsDir="/jukebox/norman/amennen/RT_prettymouth/data/bids/Norman/Mennen/5516_greenEyes"
imgDir = "/jukebox/norman/amennen/RT_prettymouth/data/conquest/{}*/dcm/"
dicomNamePattern = "{}-{}-1.dcm"
classifierDir = "/jukebox/norman/amennen/github/brainiak/rt-cloud/projects/greenEyes/cloud_code/classifiers/"
maskDir = "/jukebox/norman/amennen/github/brainiak/rt-cloud/projects/greenEyes/cloud_code/masks/"



